import { supabase } from './supabase.js'
const params=new URLSearchParams(location.search),publicSlug=params.get('slug'),pageSlug=params.get('page')||'',root=document.getElementById('siteRoot')
const{data:published,error}=publicSlug?await supabase.rpc('get_public_site',{p_slug:publicSlug}).maybeSingle():{data:null,error:null}
const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=String(text??'');return n}
const append=(parent,...children)=>{parent.append(...children.filter(Boolean));return parent}
const color=value=>/^#[0-9a-f]{6}$/i.test(value||'')?value:'#111111'
const media=value=>typeof value==='string'&&(/^https:\/\/[^\s<>"']{1,2000}$/.test(value)||(value.length<=800000&&/^data:image\/(png|jpeg|webp|gif);base64,[a-z0-9+/]+={0,2}$/i.test(value)))?value:null
const email=value=>typeof value==='string'&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)?value:''
const href=(slug='')=>`site.html?slug=${encodeURIComponent(publicSlug)}${slug?`&page=${encodeURIComponent(slug)}`:''}`
const link=(label,url,cls)=>{const a=el('a',cls,label);a.setAttribute('href',url);return a}
function navigation(data,active){const h=el('header','site-nav'),nav=el('nav');for(const p of data.pages){const a=link(p.name,href(p.slug));if(p.slug===active)a.setAttribute('aria-current','page');nav.append(a)}return append(h,link(data.businessName,href(),'brand'),nav,link('Kontakt','#kontakt','nav-cta'))}
function hero(page,data){const s=el('section','hero');s.id='top';s.style.backgroundColor=color(data.bg);const c=el('div','hero-content'),title=el('h1');String(page.heroTitle||'').split('\n').forEach((line,i)=>{if(i)title.append(document.createElement('br'));title.append(document.createTextNode(line))});return append(s,el('div','hero-orb one'),el('div','hero-orb two'),append(c,el('span','eyebrow',page.heroTag),title,el('p','',page.heroSub),append(el('div','hero-actions'),link(page.cta,'#kontakt','button'),el('span','badge',page.badge))))}
function about(page){return append(el('section','section intro'),el('span','kicker','Om bedriften'),el('h2','',page.aboutTitle),el('p','',page.aboutText))}
function offerings(page){const cards=el('div','cards');for(const o of page.offerings||[])append(cards,append(el('article'),el('h3','',o.t),el('p','',o.d),link('Les mer →','#kontakt')));return append(el('section','section offerings'),append(el('div','section-head'),append(el('div'),el('span','kicker','Utvalgt for deg'),el('h2','',page.offeringsLabel))),cards)}
function gallery(page){const grid=el('div','gallery-grid');(page.gallery||[]).forEach((g,i)=>{const tile=el('div',`gallery-tile tile-${i+1}`),url=media(g.img);if(url)tile.style.backgroundImage=`url("${url.replaceAll('"','%22')}")`;else tile.append(el('span','',g.emoji||'✦'));grid.append(tile)});return append(el('section','gallery'),append(el('div','gallery-copy'),el('span','kicker','Et lite innblikk'),el('h2','','Detaljene gjør forskjellen.')),grid)}
function contact(page,data){const s=el('section','contact'),mail=email(data.contactEmail);s.id='kontakt';s.style.backgroundColor=color(data.bg);append(s,el('span','kicker','La oss snakke sammen'),el('h2','','Klar for neste steg?'),el('p','',page.hours));if(mail)s.append(link(page.cta,`mailto:${mail}`,'button'));s.append(append(el('div','contact-meta'),el('span','',`📍 ${page.address||''}`),el('span','',mail?`✉ ${mail}`:'')));return s}
function extra(section){const s=el('section',section.id);append(s,el('span','kicker',section.id.toUpperCase()),el('h2','',section.name||''));const content=EXTRA_SECTION_CONTENT?.[section.id];for(const item of content?.items||[])s.append(el('p','',item.quote||item.q||`${item.name||''} ${item.role||''}`));return s}
function render(section,page,data){if(!section.enabled)return null;const f={hero:()=>hero(page,data),about:()=>about(page),offerings:()=>offerings(page),gallery:()=>gallery(page),contact:()=>contact(page,data),testimonials:()=>extra(section),team:()=>extra(section),faq:()=>extra(section),ctabanner:()=>extra(section)}[section.id];return f?f():null}
if(error||!published?.content)append(root,append(el('main','missing'),el('h1','','Nettsiden finnes ikke'),link('Tilbake til Wreach','index.html')))
else{const data=published.content,page=data.pages.find(p=>p.slug===pageSlug)||data.pages[0];document.title=page.slug?`${page.name} | ${data.businessName}`:(data.seoTitle||published.website_name);document.documentElement.style.setProperty('--accent',color(data.accent));document.documentElement.style.setProperty('--accent2',color(data.accent2));root.replaceChildren(navigation(data,page.slug),...(page.sections||[]).map(s=>render(s,page,data)).filter(Boolean),append(el('footer'),link(data.businessName,href(),'brand'),el('span','',`© ${new Date().getFullYear()} ${data.businessName}`),el('span','','Laget av Wreach')))}
